### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by wangyeqiang** [springMoon/sqlSubmit#6]
作者您好，我这边有一个疑问，就是现在sql-client.sh也支持文件提交了，我想问下为什么还要使用这种table API的形式去提交sql,是因为有什么好处吗？希望回答。在线等。

**Comment by Vector-Cross** [comment]
> 文

1.12版本支持吗，怎么用的呀，一直没搜到

**Comment by springMoon** [comment]
> 问

这个项目比较早了，flink 1.10 就有了，sql-client 功能很弱鸡（1.13 也是），很多功能没有
table api 是为了方便提交SQL，写 udf，checkpoint，debug 代码

**Comment by springMoon** [comment]
> > 文
> 
> 1.12版本支持吗，怎么用的呀，一直没搜到

这个是绑定版本的，有个 flink1.12 的分支
